import { PlaceHolderImages } from './placeholder-images';

export type Product = {
  id: string;
  name: string;
  price: number; // Precio al Detal
  wholesalePrice?: number; // Precio al Mayor
  originalPrice?: number; // Precio anterior para ofertas
  category: 'Tazas' | 'Franelas' | 'Llaveros' | 'Libretas' | 'Gorras' | 'Otros' | 'Ofertas' | 'Pullover' | 'Mousepad' | 'Portavasos' | 'Laminas' | 'Stickers' | 'PVC';
  stock: number;
  description: string;
  imagePlaceholderId: string;
};

export const products: Product[] = [
  // TAZAS
  {
    id: 't-magica',
    name: 'Tazas Mágicas',
    price: 10.0,
    category: 'Tazas',
    stock: 50,
    description: 'Taza sensible al calor que revela el diseño al verter líquido caliente.',
    imagePlaceholderId: 'taza-2',
  },
  {
    id: 't-glaseada-blanca',
    name: 'Tazas Glaseadas Blancas',
    price: 7.0,
    wholesalePrice: 5.0,
    category: 'Tazas',
    stock: 30,
    description: 'Taza con acabado glaseado mate elegante.',
    imagePlaceholderId: 'taza-glaseada-blanca',
  },
  {
    id: 't-glaseada-base',
    name: 'Tazas Glaseadas Base Color',
    price: 8.5,
    wholesalePrice: 7.0,
    category: 'Tazas',
    stock: 25,
    description: 'Taza glaseada con base de color vibrante.',
    imagePlaceholderId: 'taza-base-color',
  },
  {
    id: 't-blanca-6oz',
    name: 'Tazas Blancas 6oz',
    price: 5.0,
    category: 'Tazas',
    stock: 100,
    description: 'Taza blanca pequeña ideal para café expreso.',
    imagePlaceholderId: 'taza-blanca-6oz',
  },
  {
    id: 't-blanca-11oz',
    name: 'Tazas Blancas 11oz',
    price: 6.0,
    category: 'Tazas',
    stock: 150,
    description: 'Taza blanca estándar para uso diario.',
    imagePlaceholderId: 'taza-blanca-11oz',
  },
  {
    id: 't-metalizada',
    name: 'Tazas Metalizadas',
    price: 0.0,
    category: 'Tazas',
    stock: 20,
    description: 'Tazas con acabado brillante metalizado.',
    imagePlaceholderId: 'taza-metalizada',
  },
  {
    id: 't-fondo-color',
    name: 'Tazas Blancas Fondo Color',
    price: 0.0,
    category: 'Tazas',
    stock: 40,
    description: 'Taza blanca con el interior de color.',
    imagePlaceholderId: 'taza-fondo-color',
  },
  {
    id: 't-unicolor',
    name: 'Tazas Unicolor',
    price: 0.0,
    category: 'Tazas',
    stock: 35,
    description: 'Taza de un solo color sólido.',
    imagePlaceholderId: 'taza-1',
  },

  // FRANELAS
  {
    id: 'f-algodon',
    name: 'Franela Unicolor Algodón',
    price: 0.0,
    category: 'Franelas',
    stock: 80,
    description: 'Franela de algodón 100% premium.',
    imagePlaceholderId: 'franela-1',
  },
  {
    id: 'f-muselina-a',
    name: 'Franela Muselina - Unicolor',
    price: 0.0,
    category: 'Franelas',
    stock: 50,
    description: 'Franela en tela muselina, estilo unicolor.',
    imagePlaceholderId: 'franela-muselina-unicolor',
  },
  {
    id: 'f-muselina-b',
    name: 'Franela Muselina - Manga Color',
    price: 0.0,
    category: 'Franelas',
    stock: 45,
    description: 'Franela en tela muselina con mangas a color.',
    imagePlaceholderId: 'franela-1',
  },
  {
    id: 'f-muselina-c',
    name: 'Franela Muselina - Manga Cuello Color',
    price: 0.0,
    category: 'Franelas',
    stock: 40,
    description: 'Franela en tela muselina con cuello y mangas a color.',
    imagePlaceholderId: 'franela-1',
  },
  {
    id: 'f-muselina-d',
    name: 'Franela Muselina - Estilo Chemise',
    price: 0.0,
    category: 'Franelas',
    stock: 30,
    description: 'Franela estilo chemise en tela muselina.',
    imagePlaceholderId: 'franela-1',
  },
  {
    id: 'f-atletica-a',
    name: 'Franela Atlética - Unicolor',
    price: 0.0,
    category: 'Franelas',
    stock: 60,
    description: 'Franela deportiva unicolor.',
    imagePlaceholderId: 'franela-2',
  },
  {
    id: 'f-atletica-b',
    name: 'Franela Atlética - Manga Color',
    price: 0.0,
    category: 'Franelas',
    stock: 55,
    description: 'Franela deportiva con mangas a color.',
    imagePlaceholderId: 'franela-2',
  },
  {
    id: 'f-micro-durazno-a',
    name: 'Franela Micro Durazno - Unicolor',
    price: 0.0,
    category: 'Franelas',
    stock: 70,
    description: 'Franela suave micro durazno unicolor.',
    imagePlaceholderId: 'franela-1',
  },
  {
    id: 'f-fullprint-corta',
    name: 'Franela Full Print Dryfit Manga Corta',
    price: 12.0,
    category: 'Franelas',
    stock: 25,
    description: 'Franela dryfit con estampado total de alta calidad.',
    imagePlaceholderId: 'franela-2',
  },
  {
    id: 'f-fullprint-larga',
    name: 'Franela Full Print Dryfit Manga Larga',
    price: 0.0,
    category: 'Franelas',
    stock: 20,
    description: 'Franela dryfit manga larga con estampado total.',
    imagePlaceholderId: 'franela-2',
  },
  {
    id: 'f-estampado-pectoral',
    name: 'Estampado Pectoral',
    price: 0.0,
    category: 'Franelas',
    stock: 999,
    description: 'Servicio de estampado en zona pectoral.',
    imagePlaceholderId: 'franela-1',
  },

  // PULLOVER
  {
    id: 'pullover-base',
    name: 'PULLOVER',
    price: 0.0,
    category: 'Pullover',
    stock: 15,
    description: 'Pullover personalizable de alta calidad.',
    imagePlaceholderId: 'franela-1',
  },

  // LLAVEROS
  {
    id: 'll-acero-rect',
    name: 'Llavero Acero Rectangular',
    price: 4.0,
    wholesalePrice: 3.5,
    category: 'Llaveros',
    stock: 50,
    description: 'Llavero de acero inoxidable rectangular.',
    imagePlaceholderId: 'llavero-1',
  },
  {
    id: 'll-largo-doble',
    name: 'Rectangular Largo Doble Cara',
    price: 3.0,
    wholesalePrice: 2.0,
    category: 'Llaveros',
    stock: 60,
    description: 'Llavero rectangular largo con impresión en ambas caras.',
    imagePlaceholderId: 'llavero-1',
  },
  {
    id: 'll-rect-doble',
    name: 'Rectangular Doble Cara',
    price: 3.5,
    wholesalePrice: 2.8,
    category: 'Llaveros',
    stock: 80,
    description: 'Llavero rectangular estándar doble cara.',
    imagePlaceholderId: 'llavero-1',
  },
  {
    id: 'll-acero-redon',
    name: 'Rectangular Borde Acero Redondeado',
    price: 4.0,
    wholesalePrice: 3.4,
    category: 'Llaveros',
    stock: 45,
    description: 'Llavero de acero con bordes redondeados.',
    imagePlaceholderId: 'llavero-1',
  },
  {
    id: 'll-corazon-doble',
    name: 'Doble Cara Corazón',
    price: 3.5,
    wholesalePrice: 2.8,
    category: 'Llaveros',
    stock: 55,
    description: 'Llavero con forma de corazón doble cara.',
    imagePlaceholderId: 'llavero-1',
  },
  {
    id: 'll-acrilico',
    name: 'Llaveros Acrílicos',
    price: 2.2,
    wholesalePrice: 1.5,
    category: 'Llaveros',
    stock: 200,
    description: 'Llaveros ligeros de acrílico personalizado.',
    imagePlaceholderId: 'llavero-1',
  },
  {
    id: 'll-relicario',
    name: 'Relicario',
    price: 0.0,
    category: 'Llaveros',
    stock: 15,
    description: 'Llavero tipo relicario para fotos.',
    imagePlaceholderId: 'llavero-1',
  },

  // GORRAS
  {
    id: 'gorras-base',
    name: 'GORRAS',
    price: 0.0,
    category: 'Gorras',
    stock: 100,
    description: 'Gorras personalizables en varios colores.',
    imagePlaceholderId: 'gorra-1',
  },

  // LIBRETAS
  {
    id: 'lib-mini-80',
    name: 'Libreta Mini 10x14cm 80h',
    price: 0.0,
    category: 'Libretas',
    stock: 40,
    description: 'Libreta pequeña de 80 hojas.',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'lib-mini-110',
    name: 'Libreta Mini 10x14cm 110h',
    price: 19.0,
    category: 'Libretas',
    stock: 35,
    description: 'Libreta pequeña de 110 hojas.',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'lib-media-110',
    name: 'Libreta Media Carta 110h',
    price: 25.0,
    category: 'Libretas',
    stock: 25,
    description: 'Libreta tamaño media carta con 110 hojas.',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'lib-oficio-110',
    name: 'Libreta Medio Oficio 110h',
    price: 27.0,
    category: 'Libretas',
    stock: 20,
    description: 'Libreta tamaño medio oficio con 110 hojas.',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'lib-carta-110',
    name: 'Libreta Carta 110h',
    price: 34.0,
    category: 'Libretas',
    stock: 15,
    description: 'Libreta tamaño carta con 110 hojas.',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'boligrafos',
    name: 'Bolígrafos',
    price: 0.0,
    category: 'Otros',
    stock: 500,
    description: 'Bolígrafos personalizables.',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'kit-base',
    name: 'Kit',
    price: 0.0,
    category: 'Otros',
    stock: 10,
    description: 'Kits personalizados combinados.',
    imagePlaceholderId: 'libreta-1',
  },

  // MOUSEPAD
  {
    id: 'mousepad-goma',
    name: 'Mousepad Rectangular Redondeado de Goma',
    price: 0.0,
    category: 'Mousepad',
    stock: 50,
    description: 'Mousepad flexible de goma con bordes redondeados.',
    imagePlaceholderId: 'mousepad-1',
  },

  // PORTAVASOS
  {
    id: 'portavasos-red',
    name: 'Portavasos Redondo de Goma',
    price: 0.0,
    category: 'Portavasos',
    stock: 100,
    description: 'Portavasos circular de goma antideslizante.',
    imagePlaceholderId: 'mousepad-1',
  },
  {
    id: 'portavasos-cuad',
    name: 'Portavasos Cuadrado de Goma',
    price: 0.0,
    category: 'Portavasos',
    stock: 100,
    description: 'Portavasos cuadrado de goma antideslizante.',
    imagePlaceholderId: 'mousepad-1',
  },

  // LAMINAS DE ALUMINIO
  {
    id: 'lamina-a4',
    name: 'Láminas de Aluminio A4 (21 x 29,7 cm)',
    price: 14.0,
    category: 'Laminas',
    stock: 30,
    description: 'Lámina metálica A4 ideal para decoración o placas.',
    imagePlaceholderId: 'mousepad-1',
  },

  // STIKERS
  {
    id: 'st-3-medio',
    name: 'Stickers 3x3cm 1/2 Metro',
    price: 8.0,
    category: 'Stickers',
    stock: 100,
    description: 'Medio metro de stickers de 3x3cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-3-metro',
    name: 'Stickers 3x3cm 1 Metro',
    price: 15.0,
    category: 'Stickers',
    stock: 100,
    description: 'Un metro de stickers de 3x3cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-4-medio',
    name: 'Stickers 4x4cm 1/2 Metro',
    price: 8.0,
    category: 'Stickers',
    stock: 100,
    description: 'Medio metro de stickers de 4x4cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-4-metro',
    name: 'Stickers 4x4cm 1 Metro',
    price: 15.0,
    category: 'Stickers',
    stock: 100,
    description: 'Un metro de stickers de 4x4cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-5-medio',
    name: 'Stickers 5x5cm 1/2 Metro',
    price: 8.0,
    category: 'Stickers',
    stock: 100,
    description: 'Medio metro de stickers de 5x5cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-5-metro',
    name: 'Stickers 5x5cm 1 Metro',
    price: 15.0,
    category: 'Stickers',
    stock: 100,
    description: 'Un metro de stickers de 5x5cm.',
    imagePlaceholderId: 'sticker-1',
  },

  // PVC
  {
    id: 'pvc-una-cara',
    name: 'PVC una cara',
    price: 0.0,
    category: 'PVC',
    stock: 100,
    description: 'Carnet o tarjeta de PVC impresa a una cara.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'pvc-dos-caras',
    name: 'PVC dos caras',
    price: 0.0,
    category: 'PVC',
    stock: 100,
    description: 'Carnet o tarjeta de PVC impresa a doble cara.',
    imagePlaceholderId: 'sticker-1',
  },
];

export const categories = [
    { name: 'Tazas', href: '/categories/tazas' },
    { name: 'Franelas', href: '/categories/franelas' },
    { name: 'Llaveros', href: '/categories/llaveros' },
    { name: 'Libretas', href: '/categories/libretas' },
    { name: 'Gorras', href: '/categories/gorras' },
    { name: 'Stickers', href: '/categories/stickers' },
    { name: 'Ofertas', href: '/offers' },
];

export const allProductCategories = [
  'Tazas', 
  'Franelas', 
  'Llaveros', 
  'Libretas', 
  'Gorras', 
  'Otros', 
  'Pullover', 
  'Mousepad', 
  'Portavasos', 
  'Laminas', 
  'Stickers', 
  'PVC'
] as const;
