
import { PlaceHolderImages } from './placeholder-images';

export type Product = {
  id: string;
  name: string;
  price: number; // Precio al Detal
  wholesalePrice?: number; // Precio al Mayor
  originalPrice?: number; // Precio anterior para ofertas
  category: 'Tazas' | 'Franelas' | 'Llaveros' | 'Libretas' | 'Gorras' | 'Otros' | 'Ofertas' | 'Pullover' | 'Mousepad' | 'Portavasos' | 'Laminas' | 'Stickers' | 'PVC';
  stock: number;
  description: string;
  imagePlaceholderId: string;
};

export const products: Product[] = [
  // TAZAS
  {
    id: 't-magica',
    name: 'Tazas Mágicas 11oz',
    price: 10.0,
    wholesalePrice: 7.0,
    category: 'Tazas',
    stock: 50,
    description: 'Taza sensible al calor que reveals el diseño al verter líquido caliente.',
    imagePlaceholderId: 'taza-2',
  },
  {
    id: 't-glaseada-blanca',
    name: 'Tazas Glaseadas Blancas',
    price: 7.0,
    wholesalePrice: 5.0,
    category: 'Tazas',
    stock: 30,
    description: 'Taza con acabado glaseado mate elegante.',
    imagePlaceholderId: 'taza-glaseada-blanca',
  },
  {
    id: 't-glaseada-base',
    name: 'Tazas Glaseadas Base Color',
    price: 8.5,
    wholesalePrice: 7.0,
    category: 'Tazas',
    stock: 25,
    description: 'Taza glaseada con base de color vibrante.',
    imagePlaceholderId: 'taza-base-color',
  },
  {
    id: 't-tu-y-yo',
    name: 'Tazas tu y yo 11oz',
    price: 22.0,
    wholesalePrice: 20.0,
    category: 'Tazas',
    stock: 20,
    description: 'Set de dos tazas diseñadas para encajar perfectamente.',
    imagePlaceholderId: 'taza-tu-y-yo',
  },
  {
    id: 't-blanca-11oz',
    name: 'Tazas Blancas 11oz',
    price: 6.0,
    wholesalePrice: 4.5,
    category: 'Tazas',
    stock: 150,
    description: 'Taza blanca estándar para uso diario.',
    imagePlaceholderId: 'taza-blanca-11oz',
  },
  {
    id: 't-metalizada',
    name: 'Tazas Metalizadas 11oz',
    price: 12.0,
    wholesalePrice: 10.0,
    category: 'Tazas',
    stock: 20,
    description: 'Tazas con acabado brillante metalizado.',
    imagePlaceholderId: 'taza-metalizada',
  },
  {
    id: 't-tornasol',
    name: 'Tazas Tornasol 11oz',
    price: 12.0,
    wholesalePrice: 10.0,
    category: 'Tazas',
    stock: 15,
    description: 'Taza con efecto tornasol que cambia de color según el ángulo de luz.',
    imagePlaceholderId: 'taza-metalizada',
  },
  {
    id: 't-fondo-color',
    name: 'Tazas Blancas Fondo Color 11oz',
    price: 12.0,
    wholesalePrice: 10.0,
    category: 'Tazas',
    stock: 40,
    description: 'Taza blanca con el interior de color.',
    imagePlaceholderId: 'taza-fondo-color',
  },
  {
    id: 't-unicolor',
    name: 'Tazas Unicolor 11oz',
    price: 12.0,
    wholesalePrice: 10.0,
    category: 'Tazas',
    stock: 35,
    description: 'Taza de un solo color sólido.',
    imagePlaceholderId: 'taza-1',
  },
  {
    id: 't-apilables',
    name: 'Set de tazas apilables 11oz',
    price: 0.0,
    category: 'Tazas',
    stock: 10,
    description: 'Set de tazas que se pueden apilar para ahorrar espacio.',
    imagePlaceholderId: 'taza-1',
  },

  // FRANELAS
  {
    id: 'f-algodon',
    name: 'Franela Unicolor Algodón',
    price: 10.0,
    category: 'Franelas',
    stock: 80,
    description: 'Franela de algodón 100% premium. Precios: S-M-L $10.00 | XL $12.00 | XXL $13.00',
    imagePlaceholderId: 'franela-1',
  },
  {
    id: 'f-micro-durazno-blanca',
    name: 'Franela Micro Durazno - Blanca',
    price: 6.0,
    category: 'Franelas',
    stock: 70,
    description: 'Franela suave micro durazno blanca. Precios: S-M-L $6.00 | XL $7.00 | XXL $8.00',
    imagePlaceholderId: 'franela-1',
  },
  {
    id: 'f-micro-durazno-color',
    name: 'Franela Micro Durazno - Color',
    price: 10.0,
    category: 'Franelas',
    stock: 50,
    description: 'Franela suave micro durazno a color. Precios: S-M-L $10.00 | XL $12.00 | XXL $13.00',
    imagePlaceholderId: 'franela-1',
  },
  {
    id: 'f-fullprint-corta',
    name: 'Franela Full Print Dryfit Manga Corta',
    price: 13.0,
    category: 'Franelas',
    stock: 25,
    description: 'Franela dryfit con estampado total de alta calidad. Precios: S-M-L $13.00 | XL $14.00 | XXL $15.00',
    imagePlaceholderId: 'franela-2',
  },
  {
    id: 'f-fullprint-larga',
    name: 'Franela Full Print Dryfit Manga Larga',
    price: 0.0,
    category: 'Franelas',
    stock: 20,
    description: 'Franela dryfit manga larga con estampado total.',
    imagePlaceholderId: 'franela-fullprint-larga',
  },

  // Pullover
  {
    id: 'pullover-base',
    name: 'Pullover',
    price: 20.0,
    category: 'Pullover',
    stock: 15,
    description: 'Pullover personalizable de alta calidad.',
    imagePlaceholderId: 'pullover-img',
  },

  // LLAVEROS
  {
    id: 'll-acero-rect',
    name: 'Llavero Acero Rectangular borde redondeado',
    price: 5.0,
    wholesalePrice: 4.5,
    category: 'Llaveros',
    stock: 50,
    description: 'Llavero de acero inoxidable rectangular.',
    imagePlaceholderId: 'llavero-acero-rectangular-img',
  },
  {
    id: 'll-largo-doble',
    name: 'Rectangular Largo Doble Cara',
    price: 4.0,
    wholesalePrice: 3.5,
    category: 'Llaveros',
    stock: 60,
    description: 'Llavero rectangular largo con impresión en ambas caras.',
    imagePlaceholderId: 'llavero-largo-doble-img',
  },
  {
    id: 'll-rect-doble',
    name: 'Rectangular Doble Cara',
    price: 4.0,
    wholesalePrice: 3.5,
    category: 'Llaveros',
    stock: 80,
    description: 'Llavero rectangular estándar doble cara.',
    imagePlaceholderId: 'llavero-1',
  },
  {
    id: 'll-acero-redon',
    name: 'Llavero Rectangular Acero',
    price: 5.0,
    wholesalePrice: 4.5,
    category: 'Llaveros',
    stock: 45,
    description: 'Llavero de acero con bordes redondeados de alta resistencia.',
    imagePlaceholderId: 'llavero-rectangular-acero-nuevo',
  },
  {
    id: 'll-corazon-doble',
    name: 'Llavero acero de corazón',
    price: 5.0,
    wholesalePrice: 4.5,
    category: 'Llaveros',
    stock: 55,
    description: 'Llavero de acero con forma de corazón, ideal para parejas.',
    imagePlaceholderId: 'llavero-corazon-img',
  },
  {
    id: 'll-acrilico',
    name: 'Llaveros Acrílicos',
    price: 2.2,
    wholesalePrice: 1.5,
    category: 'Llaveros',
    stock: 200,
    description: 'Llaveros ligeros de acrílico personalizado.',
    imagePlaceholderId: 'llavero-acrilico-img',
  },
  {
    id: 'll-relicario',
    name: 'Relicario',
    price: 7.0,
    wholesalePrice: 6.0,
    category: 'Llaveros',
    stock: 15,
    description: 'Llavero tipo relicario para fotos memorables.',
    imagePlaceholderId: 'relicario-img',
  },

  // GORRAS
  {
    id: 'gorras-base',
    name: 'Gorras',
    price: 0.0,
    category: 'Gorras',
    stock: 100,
    description: 'Gorras personalizables en varios colores.',
    imagePlaceholderId: 'gorra-1',
  },

  // LIBRETAS
  {
    id: 'lib-mini-80',
    name: 'Libreta Mini 10x14cm 80 hh',
    price: 10.0,
    category: 'Libretas',
    stock: 40,
    description: 'Descripción\n- Portada dura\n- Incluye logo o nombre en cada página y en portada\n- Calendario',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'lib-mini-110',
    name: 'Libreta Mini 10x14cm 110 hh',
    price: 12.0,
    category: 'Libretas',
    stock: 35,
    description: 'Descripción\n- Portada dura\n- Incluye logo o nombre en cada página y en portada\n- Calendario',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'lib-media-110',
    name: 'Libreta Media Carta 110 hh',
    price: 16.0,
    category: 'Libretas',
    stock: 25,
    description: 'Descripción\n- Portada dura\n- Incluye logo o nombre en cada página y en portada\n- Calendario',
    imagePlaceholderId: 'libreta-1',
  },
  {
    id: 'lib-oficio-110',
    name: 'Libreta Medio Oficio 110 hh',
    price: 18.0,
    category: 'Libretas',
    stock: 20,
    description: 'Descripción\n- Portada dura\n- Incluye logo o nombre en cada página y en portada\n- Calendario',
    imagePlaceholderId: 'libreta-1',
  },

  // OTROS Y KITS
  {
    id: 'kit-mini-10x14',
    name: 'Kit Mini 10cm X 14cm',
    price: 19.0,
    category: 'Otros',
    stock: 15,
    description: '- Bolígrafo\n- Libreta\n- Taza\n\nDescripción\n- Con logo o nombre personalizado\n- 110 hojas\n- Interior blanco y negro',
    imagePlaceholderId: 'kit-img',
  },
  {
    id: 'kit-media-carta',
    name: 'Kit Media Carta',
    price: 25.0,
    category: 'Otros',
    stock: 15,
    description: '- Bolígrafo\n- Libreta\n- Taza\n\nDescripción\n- Con logo o nombre personalizado\n- 110 hojas\n- Interior blanco y negro',
    imagePlaceholderId: 'kit-img',
  },
  {
    id: 'kit-medio-oficio',
    name: 'Kit Medio Oficio',
    price: 27.0,
    category: 'Otros',
    stock: 15,
    description: '- Bolígrafo\n- Libreta\n- Taza\n\nDescripción\n- Con logo o nombre personalizado\n- 110 hojas\n- Interior blanco y negro',
    imagePlaceholderId: 'kit-img',
  },

  // MOUSEPAD
  {
    id: 'mousepad-goma',
    name: 'Mousepad Rectangular Redondeado de Goma',
    price: 0.0,
    category: 'Mousepad',
    stock: 50,
    description: 'Mousepad flexible de goma con bordes redondeados.',
    imagePlaceholderId: 'mousepad-1',
  },

  // PORTAVASOS
  {
    id: 'portavasos-red',
    name: 'Portavasos Redondo de Goma',
    price: 0.0,
    category: 'Portavasos',
    stock: 100,
    description: 'Portavasos circular de goma antideslizante.',
    imagePlaceholderId: 'portavasos-redondo-img',
  },
  {
    id: 'portavasos-cuad',
    name: 'Portavasos Cuadrado de Goma',
    price: 0.0,
    category: 'Portavasos',
    stock: 100,
    description: 'Portavasos cuadrado de goma antideslizante.',
    imagePlaceholderId: 'mousepad-1',
  },

  // LAMINAS DE ALUMINIO
  {
    id: 'lamina-a4',
    name: 'Lámina de Aluminio A4 (21 x 29,7 cm)',
    price: 14.0,
    category: 'Laminas',
    stock: 30,
    description: 'Lámina metálica A4 ideal para decoración o placas.',
    imagePlaceholderId: 'lamina-aluminio-a4-img',
  },
  {
    id: 'lamina-a5',
    name: 'Lámina de Aluminio A5 14.8cm X 21cm',
    price: 10.0,
    category: 'Laminas',
    stock: 30,
    description: 'Lámina metálica A5 ideal para decoración o placas.',
    imagePlaceholderId: 'lamina-aluminio-a5-img',
  },
  {
    id: 'lamina-a6',
    name: 'Lámina de Aluminio A6 10.5cm X 14.8cm',
    price: 7.0,
    category: 'Laminas',
    stock: 30,
    description: 'Lámina metálica A6 ideal para decoración o placas.',
    imagePlaceholderId: 'lamina-aluminio-a6-img',
  },

  // Stickers
  {
    id: 'st-3-medio',
    name: 'Stickers 3x3cm 1/2 Metro',
    price: 8.0,
    category: 'Stickers',
    stock: 100,
    description: 'Medio metro de stickers de 3x3cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-3-metro',
    name: 'Stickers 3x3cm 1 Metro',
    price: 12.0,
    category: 'Stickers',
    stock: 100,
    description: 'Un metro de stickers de 3x3cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-4-medio',
    name: 'Stickers 4x4cm 1/2 Metro',
    price: 8.0,
    category: 'Stickers',
    stock: 100,
    description: 'Medio metro de stickers de 4x4cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-4-metro',
    name: 'Stickers 4x4cm 1 Metro',
    price: 12.0,
    category: 'Stickers',
    stock: 100,
    description: 'Un metro de stickers de 4x4cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-5-medio',
    name: 'Stickers 5x5cm 1/2 Metro',
    price: 8.0,
    category: 'Stickers',
    stock: 100,
    description: 'Medio metro de stickers de 5x5cm.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'st-5-metro',
    name: 'Stickers 5x5cm 1 Metro',
    price: 12.0,
    category: 'Stickers',
    stock: 100,
    description: 'Un metro de stickers de 5x5cm.',
    imagePlaceholderId: 'sticker-1',
  },

  // PVC
  {
    id: 'pvc-una-cara',
    name: 'PVC una cara x 100',
    price: 20.0,
    category: 'PVC',
    stock: 100,
    description: 'Carnet o tarjeta de PVC impresa a una cara.',
    imagePlaceholderId: 'sticker-1',
  },
  {
    id: 'pvc-dos-caras',
    name: 'PVC dos caras x 100',
    price: 25.0,
    category: 'PVC',
    stock: 100,
    description: 'Carnet o tarjeta de PVC impresa a doble cara.',
    imagePlaceholderId: 'sticker-1',
  },
];

export const categories = [
    { name: 'Catálogo', href: '/categories' },
    { name: 'Tazas', href: '/categories/tazas' },
    { name: 'Franelas', href: '/categories/franelas' },
    { name: 'Llaveros', href: '/categories/llaveros' },
    { name: 'Libretas', href: '/categories/libretas' },
    { name: 'Gorras', href: '/categories/gorras' },
    { name: 'Stickers', href: '/categories/stickers' },
    { name: 'Ofertas', href: '/offers' },
];

export const allProductCategories = [
  'Tazas', 
  'Franelas', 
  'Llaveros', 
  'Libretas', 
  'Gorras', 
  'Otros', 
  'Pullover', 
  'Mousepad', 
  'Portavasos', 
  'Laminas', 
  'Stickers', 
  'PVC'
] as const;
